spring:
  application:
    name: salon-payment-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/salon_payment_service
    username: root
    password: "Calm032@@"      # quoted due to special chars
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

server:
  port: 5006

# Security (Deprecated in Spring Boot 3+)
security:
  basic:
    enable: false
  ignored: /**

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

stripe:
  api:
    key: "ddsf"
    secret: "avsghsg"

razorpay:
  api:
    key: "fsfs"
    secret: "sfsdf"